if(!API_BASE)document.getElementById('local-llm-nav')?.removeAttribute('hidden');
import {API_BASE} from './config.js';
if(!API_BASE)document.getElementById('model-plugins-nav')?.removeAttribute('hidden');
let lastGeneratedPrompt='';
import {createExamplePrompts} from './prompts.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={school:'M3 21h18M5 21V8l7-5 7 5v13M9 21v-5h6v5M8 10h1m6 0h1M8 13h1m6 0h1',culture:'M4 5h16v14H4zM8 5v14M16 5v14M4 9h16M4 15h16',park:'m12 2-6 7h3l-5 7h6v6h4v-6h6l-5-7h3z',catalog:'M5 4h14v16H5zM8 8h8M8 12h8M8 16h5',people:'M15 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2M17 15a4 4 0 0 1 4 4v2M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M17 3a4 4 0 0 1 0 8',trend:'m3 17 6-6 4 4 8-10M15 5h6v6',chart:'M4 3v17h17M8 16v-5M13 16V7M18 16v-8',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',history:'M3 11a9 9 0 1 1 2 7M3 4v7h7M12 7v5l3 2',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',info:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20M12 10v7M12 6v1',link:'m10 13 4-4M8 15l-2 2a4 4 0 0 1-5-5l4-4a4 4 0 0 1 5 0M14 9l2-2a4 4 0 0 1 5 5l-4 4a4 4 0 0 1-5 0'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.catalog}"/></svg>`;}
$$('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));
let catalog=[],selected=new Set(['population','fertility']),filter='all',result=null,view='dashboard',busy=false,timer,logs=[],history=[];
try{history=JSON.parse(localStorage.getItem('ondata-history')||'[]');if(!Array.isArray(history))history=[];}catch{}
function safeUrl(u){try{const p=new URL(u);return ['https:','http:'].includes(p.protocol)?p.href:'#';}catch{return '#';}}
function sourceName(id){return catalog.find(s=>s.id===id)?.name||id;}
function renderCards(){
 const query=$('#source-search').value.toLowerCase();const visible=catalog.filter(s=>(filter==='all'||s.type===filter||s.category===filter)&&(!$('#available-only').checked||s.available)&&`${s.name} ${s.provider} ${s.category}`.toLowerCase().includes(query));
 $('#source-grid').innerHTML=visible.length?visible.map(s=>`<article class="source-card ${selected.has(s.id)?'selected':''} ${s.available?'':'disabled'}"><input class="card-toggle" type="checkbox" aria-label="${esc(s.name)} 선택" data-select="${s.id}" ${selected.has(s.id)?'checked':''} ${s.available&&!busy?'':'disabled'}><div class="card-top"><div class="source-icon ${s.color}">${icon(s.icon)}</div><span class="card-check">✓</span></div><h3 class="card-name">${esc(s.name)}</h3><p class="provider">${esc(s.provider)}</p><p class="card-description">${esc(s.description)}<br><strong>정량 지표: ${esc(s.numericFields.join(' · '))} (${esc(s.unit)})</strong></p><div class="card-bottom"><span class="type-badge ${s.type==='MCP'?'mcp':''}">${s.type}</span><span>${esc(s.auth)}</span><button class="detail-button" data-detail="${s.id}" aria-label="${esc(s.name)} 상세 정보">ⓘ</button></div></article>`).join(''):'<p class="empty-state">검색 조건에 맞는 소스가 없습니다.</p>';
 $$('[data-select]').forEach(e=>e.addEventListener('change',()=>{e.checked?selected.add(e.dataset.select):selected.delete(e.dataset.select);invalidate();renderCards();renderSelection();refreshExamples();}));
 $$('[data-detail]').forEach(e=>e.addEventListener('click',()=>{const s=catalog.find(s=>s.id===e.dataset.detail);$('#source-detail').innerHTML=`<span class="type-badge">${s.type} · ${esc(s.category)}</span><h2>${esc(s.name)}</h2><p>${esc(s.provider)}</p><p>${esc(s.description)}</p><p><strong>조회 범위</strong><br>${esc(s.scope)}</p><p><strong>연결 조건</strong><br>${esc(s.auth)}</p><p>${esc(s.origin)}</p><a href="${safeUrl(s.url)}" target="_blank" rel="noreferrer">원천 서비스 · 문서 열기 ↗</a>`;$('#source-dialog').showModal();}));
}
function invalidate(){result=null;$('#results').hidden=true;$('#error').hidden=true;$('#getting-started').hidden=false;}
function renderSelection(){
 $('#selection-count').textContent=`${selected.size}개 선택됨`;
 $('#selected-chips').innerHTML=[...selected].map(id=>`<span class="source-chip">${esc(sourceName(id))}<button data-remove="${id}" aria-label="${esc(sourceName(id))} 선택 해제" ${busy?'disabled':''}>×</button></span>`).join('');
 $$('[data-remove]').forEach(e=>e.onclick=()=>{selected.delete(e.dataset.remove);invalidate();renderCards();renderSelection();refreshExamples();});updateButtons();
}
function updateButtons(){$('#analyze').disabled=busy||!selected.size||!$('#prompt').value.trim();$('#preview').disabled=busy||!selected.size;}
function params(){return {prompt:$('#prompt').value.trim()||'선택된 데이터를 미리 보여 주세요.',sourceIds:[...selected],region:$('#region').value,observationDate:$('#observation-date').value,startYear:Number($('#start-year').value),endYear:Number($('#end-year').value),keyword:$('#keyword').value};}
function setBusy(value){busy=value;$$('#prompt,.query-fields input,.query-fields select,[data-example],#suggestions button,#new-analysis').forEach(e=>e.disabled=value);renderCards();renderSelection();}
function showError(message){$('#error').textContent=message;$('#error').hidden=false;}
function log(event){logs.push({...event,time:new Date().toISOString()});$('#progress-title').textContent=event.message;const line=document.createElement('div');line.textContent=`${event.stage==='source_error'?'!':'✓'} ${event.message}`;$('#progress-log').append(line);if(event.stage==='analyze')$('#progress-title').textContent='선택한 데이터에서 인사이트를 찾는 중';}
async function run(preview=false){
 if(busy)return;const p=params();invalidate();logs=[];setBusy(true);$('#progress').hidden=false;$('#progress .spinner').hidden=false;$('#progress-log').innerHTML='';$('#progress-title').textContent=preview?'선택한 원자료를 조회하는 중':'데이터를 연결하고 있습니다';const start=Date.now();$('#elapsed').textContent='0초';timer=setInterval(()=>$('#elapsed').textContent=`${Math.floor((Date.now()-start)/1000)}초`,1000);
 try{
  const response=await fetch(API_BASE+(preview?'/api/preview':'/api/analyze'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});
  if(!response.ok){const error=await response.json();throw new Error(error.error||'요청 처리 실패');}
  if(preview){const data=await response.json();result={...data,params:p,createdAt:new Date().toISOString(),preview:true};view='table';}
  else{
   const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',completed=false;
   const consume=line=>{if(!line.trim())return;const event=JSON.parse(line);if(event.message&&event.stage!=='error')log(event);if(event.stage==='data')result={datasets:event.datasets,params:p,createdAt:new Date().toISOString(),preview:true};if(event.stage==='complete'){result={...event,logs};completed=true;}if(event.stage==='error')throw new Error(event.message);};
   while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines)consume(line);}if(buffer.trim())consume(buffer);if(!completed)throw new Error('분석 연결이 완료 전에 종료됐습니다. 확보된 원자료를 확인해 주세요.');
   saveHistory();
  }
 }catch(e){showError(e.message);if(result)view='table';}
 finally{clearInterval(timer);setBusy(false);$('#progress').hidden=preview;$('#progress .spinner').hidden=true;$('#progress-title').textContent='분석 과정 · 실행 기록';if(result){$('#results').hidden=false;$('#getting-started').hidden=true;renderResult();$('#results').scrollIntoView({behavior:'smooth',block:'start'});}}
}
function metricCards(){const data=result.datasets.filter(d=>!d.error);return `<div class="metric-grid"><div class="metric"><span>사용한 데이터 소스</span><strong>${data.length}<small>선택 ${result.params.sourceIds.length}개 중 조회 성공</small></strong></div><div class="metric"><span>실제 조회된 레코드</span><strong>${data.reduce((n,d)=>n+d.rows.length,0).toLocaleString()}<small>유효·결측 행 포함 · 정량 원자료</small></strong></div><div class="metric"><span>조회 기준 시각</span><strong style="font-size:19px">${new Date(result.createdAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}<small>${new Date(result.createdAt).toLocaleDateString('ko-KR')}</small></strong></div></div>`;}
function lineChart(d,mode='line'){
 const rows=d.rows.filter(r=>typeof r.값==='number'&&Number.isFinite(r.값));if(!rows.length)return '<p class="muted">수치 데이터가 없습니다.</p>';
 const width=520,height=225,left=65,right=15,top=20,bottom=38;let min=mode==='bar'?Math.min(0,...rows.map(r=>r.값)):Math.min(...rows.map(r=>r.값)),max=Math.max(...rows.map(r=>r.값),...(mode==='bar'?[0]:[]));const delta=max-min||1;if(mode==='line'){min-=delta*.12;max+=delta*.12;}
 const minYear=Math.min(...d.rows.map(r=>r.연도)),maxYear=Math.max(...d.rows.map(r=>r.연도));const x=r=>left+(r.연도-minYear)/(maxYear-minYear||1)*(width-left-right),y=v=>height-bottom-(v-min)/(max-min||1)*(height-top-bottom);
 const fmt=v=>Math.abs(v)>=1000000?(v/1000000).toFixed(1)+'백만':v.toFixed(2);
 let svg=`<svg class="chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(d.name)} 연도별 ${mode==='bar'?'막대':'추이'} 차트">`;
 for(let i=0;i<4;i++){const v=min+(max-min)*i/3,yy=y(v);svg+=`<line x1="${left}" x2="${width-right}" y1="${yy}" y2="${yy}" stroke="#eaf0ed"/><text x="${left-10}" y="${yy+3}" text-anchor="end">${fmt(v)}</text>`;}
 if(mode==='line'){
  // Break the line across missing years; do not interpolate gaps as observed values.
  let path='',previous;for(const r of rows){path+=`${previous!==undefined&&r.연도===previous+1?'L':'M'}${x(r)},${y(r.값)} `;previous=r.연도;}
  svg+=`<path d="${path}" fill="none" stroke="#36a189" stroke-width="2.5"/>`;
 }
 const barWidth=Math.min(24,(width-left-right)/(maxYear-minYear+1)*.55);
 rows.forEach((r,i)=>{svg+=mode==='bar'?`<rect x="${x(r)-barWidth/2}" y="${Math.min(y(r.값),y(0))}" width="${barWidth}" height="${Math.abs(y(0)-y(r.값))}" rx="3" fill="#6bb39c"><title>${r.연도}: ${r.값.toLocaleString()} ${esc(r.단위)}</title></rect>`:`<circle cx="${x(r)}" cy="${y(r.값)}" r="3" fill="#fff" stroke="#36a189" stroke-width="2"><title>${r.연도}: ${r.값.toLocaleString()} ${esc(r.단위)}</title></circle>`;if(i%Math.max(1,Math.ceil(rows.length/6))===0||i===rows.length-1)svg+=`<text x="${x(r)}" y="${height-15}" text-anchor="middle">${r.연도}</text>`;});return svg+'</svg>';
}
function categoryChart(d){if(d.numericFields?.length){const field=d.numericFields[0];const rows=d.rows.filter(r=>Number.isFinite(r[field]));const max=Math.max(...rows.map(r=>r[field]),1);return `<p class="muted">${esc(field)} · ${esc(d.unit)}</p>`+rows.map(r=>`<div class="bar-row"><span>${esc(r.역명||r.대여소)}</span><div class="bar-track"><div class="bar-fill" style="width:${r[field]/max*100}%"></div></div><strong>${r[field].toLocaleString()}</strong></div>`).join('');}const key=d.id==='schools'?'설립구분':d.id==='culture'?'분류':d.id==='parks'?'지역':null;if(!key)return `<p class="muted">메타데이터 검색 결과 ${d.rows.length}건입니다. 데이터 테이블에서 후보와 원천 링크를 확인하세요.</p>`;const groups={};d.rows.forEach(r=>groups[r[key]||'미상']=(groups[r[key]||'미상']||0)+1);const max=Math.max(...Object.values(groups),1);return Object.entries(groups).map(([name,n])=>`<div class="bar-row"><span>${esc(name)}</span><div class="bar-track"><div class="bar-fill" style="width:${n/max*100}%"></div></div><strong>${n}건</strong></div>`).join('');}
function dashboard(){
 const r=result.report;return `${r?`<div class="result-summary"><div class="eyebrow">✦ ${esc(result.model)} · GROUNDED ANALYSIS</div><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p></div>`:'<div class="empty-state">원자료 미리보기입니다. AI 분석을 실행하면 요약과 해석이 추가됩니다.</div>'}${metricCards()}<div class="chart-grid">${result.datasets.filter(d=>!d.error).map(d=>`<article class="panel">${d.metadata?.indicator?`<select class="chart-mode" data-chart="${d.id}" aria-label="${esc(d.name)} 차트 종류"><option value="line">추이선</option><option value="bar">막대</option></select>`:''}<h3>${esc(d.name)}</h3><div id="chart-${d.id}">${d.metadata?.indicator?lineChart(d):categoryChart(d)}</div><p class="scope">${esc(d.scope)}</p></article>`).join('')}</div>${r?findingsHtml(r):''}`;
}
function findingsHtml(r){return r.findings.map(f=>`<article class="panel"><h3>${esc(f.title)}</h3><p class="report-block">${esc(f.body)}</p>${f.sourceIds.map(id=>`<span class="evidence-tag">${esc(sourceName(id))}</span>`).join('')}</article>`).join('');}
function reportHtml(){const r=result.report;if(!r)return '<div class="empty-state">AI 보고서가 아직 없습니다. AI 분석을 실행해 주세요.</div>';return `<div class="panel"><div class="eyebrow">공공데이터 분석 보고서</div><h1 class="report-title">${esc(r.title)}</h1><p>${esc(result.params.prompt)}</p><p class="scope">${new Date(result.createdAt).toLocaleString('ko-KR')} · ${esc(result.model)} · AI 해석은 원자료와 대조해 검토하세요.</p><h3>핵심 요약</h3><p class="report-block">${esc(r.summary)}</p></div>${findingsHtml(r)}<div class="panel"><h3>추가 검토 제안</h3><ul>${r.recommendations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="panel"><h3>분석의 범위와 한계</h3><ul>${[...r.limitations,...result.datasets.filter(d=>d.scope).map(d=>`${d.name}: ${d.scope}`),...result.datasets.filter(d=>d.error).map(d=>`${d.name}: 조회 실패 (${d.error})`)].map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>${evidenceHtml(false)}`;}
function displayCell(v){if(v===null||v===undefined)return '—';if(typeof v==='number')return v.toLocaleString('ko-KR',{maximumFractionDigits:6});if(typeof v==='object')return esc(JSON.stringify(v));if(/^https?:\/\//.test(v))return `<a href="${esc(safeUrl(v))}" target="_blank" rel="noreferrer">공식 링크 ↗</a>`;return esc(v);}
function tableHtml(){return result.datasets.map(d=>{if(d.error)return `<div class="panel"><h3>${esc(d.name)}</h3><p>조회 실패: ${esc(d.error)}</p></div>`;const keys=[...new Set(d.rows.flatMap(Object.keys))];return `<section class="panel"><div class="table-tools"><h3>${esc(d.name)} <span class="row-count">${d.rows.length}건</span></h3><input data-table-search="${d.id}" aria-label="${esc(d.name)} 행 검색" placeholder="결과 내 검색"></div><div class="table-wrap"><table id="table-${d.id}"><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${d.rows.map(r=>`<tr>${keys.map(k=>`<td title="${esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])}">${displayCell(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${!d.rows.length?'<p class="muted">검색 결과가 없습니다. MCP 검색어를 더 짧은 핵심어로 입력해 보세요.</p>':''}<p class="scope">${esc(d.scope)} · 조회 ${esc(d.retrievedAt)}</p></section>`;}).join('');}
function mapHtml(){const points=result.datasets.filter(d=>!d.error).flatMap(d=>d.rows.filter(r=>Number.isFinite(r.위도)&&Number.isFinite(r.경도)&&r.위도>=-90&&r.위도<=90&&r.경도>=-180&&r.경도<=180&&r.위도!==0&&r.경도!==0).map(r=>({lat:r.위도,lon:r.경도,name:r.공원명||r.행사명||r.장소명||r.대여소,source:d.name})));if(!points.length)return '<div class="empty-state">선택한 데이터에 좌표가 없습니다. 서울 따릉이 대여소 현황 카드를 선택해 주세요.</div>';const minX=Math.min(...points.map(p=>p.lon))-.015,maxX=Math.max(...points.map(p=>p.lon))+.015,minY=Math.min(...points.map(p=>p.lat))-.01,maxY=Math.max(...points.map(p=>p.lat))+.01;const x=v=>70+(v-minX)/(maxX-minX)*700,y=v=>280-(v-minY)/(maxY-minY)*220;let svg='<svg class="map-plot" viewBox="0 0 840 330" role="img" aria-label="조회한 위치의 경도·위도 좌표 분포">';for(let i=0;i<5;i++){const lon=minX+(maxX-minX)*i/4,lat=minY+(maxY-minY)*i/4;svg+=`<line x1="${x(lon)}" x2="${x(lon)}" y1="45" y2="280" stroke="#dce8df"/><text x="${x(lon)}" y="305" text-anchor="middle">${lon.toFixed(3)}° E</text><line x1="70" x2="770" y1="${y(lat)}" y2="${y(lat)}" stroke="#dce8df"/><text x="5" y="${y(lat)+3}">${lat.toFixed(3)}° N</text>`;}points.forEach((p,i)=>svg+=`<circle cx="${x(p.lon)}" cy="${y(p.lat)}" r="9"><title>${esc(p.name)} (${p.lat}, ${p.lon})</title></circle><text x="${x(p.lon)+12}" y="${y(p.lat)-8}">${i+1}</text>`);return `<div class="panel"><h3>조회 지점의 공간 분포</h3><p>선택한 데이터의 경위도를 표시합니다. 배경지도·행정경계가 없는 좌표 분포도이며, 거리·생활권 분석 결과가 아닙니다.</p>${svg}</svg><div class="map-legend">${points.map((p,i)=>`<span>${i+1}. ${esc(p.name)}</span>`).join('')}</div><p class="scope">외부 지도 서비스를 추가 조회하지 않습니다. 표본 지점만 표시합니다.</p></div>`;}
function evidenceHtml(withLogs=true){return result.datasets.map(d=>`<article class="panel"><h3>${esc(d.name)} ${d.error?'· 조회 실패':'· 조회 성공'}</h3>${d.error?`<p>${esc(d.error)}</p>`:`<p>${esc(d.provider)} · ${esc(d.type)} · ${d.rows.length}건</p><p>${esc(d.scope)}</p><a class="source-link" href="${esc(safeUrl(d.url))}" target="_blank" rel="noreferrer">${esc(d.url)}</a><p>조회 시각 ${esc(d.retrievedAt)} · ${d.durationMs}ms${d.metadata.updated?' · 제공기관 갱신 '+esc(d.metadata.updated):''}${d.metadata.snapshot?' · 스냅샷 '+esc(d.metadata.snapshot):''}</p>`}</article>`).join('')+(withLogs?`<div class="panel"><h3>실행 기록</h3><p>허용 소스: ${result.params.sourceIds.map(sourceName).map(esc).join(', ')}</p>${(result.logs||[]).map(l=>`<p>${esc(l.time)} · ${esc(l.message)}</p>`).join('')}<p>차트·표는 원자료에서 직접 생성합니다. AI 문장은 자동 사실 검증을 보장하지 않으며, 표시된 근거와 대조할 수 있습니다.</p></div>`:'');}
function renderResult(){if(!result)return;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#result-status').textContent=result.report?'AI 분석 완료':'원자료 미리보기 · AI 해석 없음';$('#result-content').innerHTML=({dashboard,report:reportHtml,table:tableHtml,map:mapHtml,evidence:evidenceHtml}[view]||dashboard)();$$('[data-chart]').forEach(el=>el.onchange=()=>{$(`#chart-${el.dataset.chart}`).innerHTML=lineChart(result.datasets.find(d=>d.id===el.dataset.chart),el.value);});$$('[data-table-search]').forEach(el=>el.oninput=()=>{$$(`#table-${el.dataset.tableSearch} tbody tr`).forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(el.value.toLowerCase()));});$('#export-md').disabled=!result.report;$('#export-html').disabled=!result.report;}
function saveHistory(){if(!result?.report)return;history.unshift(result);history=history.slice(0,10);try{localStorage.setItem('ondata-history',JSON.stringify(history));}catch{showError('분석은 완료됐지만 브라우저 저장 공간 부족으로 기록을 저장하지 못했습니다. 결과를 내려받아 주세요.');}$('#history-count').textContent=history.length;}
function renderHistory(){$('#history-count').textContent=history.length;$('#history-list').innerHTML=history.length?history.map((r,i)=>`<article class="history-item"><div><h3>${esc(r.report.title)}</h3><small>${new Date(r.createdAt).toLocaleString('ko-KR')} · ${r.params.sourceIds.map(sourceName).map(esc).join(', ')}</small></div><button class="button secondary" data-history="${i}">결과 열기 →</button></article>`).join(''):'<div class="empty-state">아직 저장된 분석이 없습니다.</div>';$$('[data-history]').forEach(e=>e.onclick=()=>{if(busy)return;const saved=history[Number(e.dataset.history)];if(saved.params.sourceIds.some(id=>!catalog.some(s=>s.id===id))){showError('이 기록은 이전 데이터 목록으로 생성됐습니다. 현재 정량 카드를 선택해 새 분석을 시작해 주세요.');navigate('workspace');return;}result=saved;selected=new Set(result.params.sourceIds);$('#prompt').value=result.params.prompt;$('#region').value=result.params.region;$('#start-year').value=result.params.startYear;$('#end-year').value=result.params.endYear;$('#keyword').value=result.params.keyword||'';$('#observation-date').value=result.params.observationDate||$('#observation-date').value;view='dashboard';navigate('workspace');renderCards();renderSelection();$('#char-count').textContent=`${$('#prompt').value.length} / 2,000`;$('#results').hidden=false;$('#getting-started').hidden=true;renderResult();$('#results').scrollIntoView({behavior:'smooth'});});}
function navigate(page){$('#history-panel').hidden=page!=='history';$('#workspace').hidden=page==='history';$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));$('#page-title').textContent=page==='history'?'분석 기록':page==='sources'?'데이터 소스':'새 분석';if(page==='history')renderHistory();if(page==='sources')$('#sources-section').scrollIntoView({behavior:'smooth'});}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function markdown(){const r=result.report;return `# ${r.title}\n\n${r.summary}\n\n## 분석 질문\n${result.params.prompt}\n\n${r.findings.map(f=>`## ${f.title}\n${f.body}\n\n근거: ${f.sourceIds.map(sourceName).join(', ')}`).join('\n\n')}\n\n## 검토 제안\n${r.recommendations.map(v=>'- '+v).join('\n')}\n\n## 한계\n${r.limitations.map(v=>'- '+v).join('\n')}\n\n## 출처\n${result.datasets.map(d=>`- ${d.name}: ${d.error?'조회 실패 '+d.error:d.url+' (조회: '+d.retrievedAt+') · '+d.scope}`).join('\n')}\n\n생성: ${result.createdAt} · ${result.model}\n`;}
$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderCards();});$('#source-search').oninput=renderCards;$('#available-only').onchange=renderCards;
$('#prompt').oninput=()=>{$('#char-count').textContent=`${$('#prompt').value.length} / 2,000`;updateButtons();};
$$('[data-format]').forEach(b=>b.onclick=()=>{view=b.dataset.format;$$('[data-format]').forEach(x=>x.classList.toggle('active',x===b));if(result)renderResult();});$$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;renderResult();});
$('#preview').onclick=()=>run(true);$('#analyze').onclick=()=>run();$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));
$('#new-analysis').onclick=()=>{invalidate();selected.clear();$('#prompt').value='';$('#keyword').value='';$('#char-count').textContent='0 / 2,000';navigate('workspace');renderCards();renderSelection();refreshExamples();window.scrollTo({top:0,behavior:'smooth'});};
$('#clear-history').onclick=()=>{history=[];localStorage.removeItem('ondata-history');renderHistory();};
$('#export-json').onclick=()=>download('온데이터-분석.json',JSON.stringify(result,null,2),'application/json');
$('#export-csv').onclick=()=>{const records=result.datasets.filter(d=>!d.error).flatMap(d=>d.rows.map(r=>({소스:d.name,조회시각:d.retrievedAt,조회범위:d.scope,...r})));const keys=[...new Set(records.flatMap(Object.keys))];const cell=v=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};download('온데이터-원자료.csv','\ufeff'+[keys,...records.map(r=>keys.map(k=>typeof r[k]==='object'?JSON.stringify(r[k]):r[k]))].map(row=>row.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');};
$('#export-md').onclick=()=>{if(result.report)download('온데이터-보고서.md',markdown(),'text/markdown;charset=utf-8');};
$('#export-html').onclick=async()=>{if(!result.report)return;const css=await fetch('./style.css').then(r=>r.text());download('온데이터-보고서.html',`<!doctype html><html lang="ko"><meta charset="utf-8"><title>${esc(result.report.title)}</title><style>${css}</style><body><div class="export-report" style="max-width:1000px;margin:auto">${reportHtml()}${metricCards()}<div class="chart-grid">${result.datasets.filter(d=>!d.error).map(d=>`<div class="panel"><h3>${esc(d.name)}</h3>${d.metadata?.indicator?lineChart(d):categoryChart(d)}</div>`).join('')}</div>${tableHtml()}</div></body></html>`,'text/html;charset=utf-8');};
$('#print').onclick=()=>{if(result?.report)view='report';renderResult();window.print();};
try{const res=await fetch(API_BASE+'/api/catalog');if(!res.ok)throw new Error('소스 목록을 불러오지 못했습니다.');const data=await res.json();catalog=data.sources;document.querySelector('.private-note').textContent=data.provider==='local'?'선택한 데이터를 로컬 LLM으로 분석합니다':'선택한 데이터가 MiniMax로 전송됩니다';$('#source-total').textContent=catalog.length;$('#filter-total').textContent=catalog.length;$('#observation-date').value=data.defaultObservationDate;$('#region').innerHTML=data.regions.map(r=>`<option>${r}</option>`).join('');$('#model-badge').textContent=`✦ ${data.model}`;if(!data.configured)showError('원자료 미리보기는 바로 사용할 수 있습니다. AI 분석에는 서버 .env의 MiniMax 키 설정이 필요합니다.');renderCards();renderSelection();renderHistory();refreshExamples();}catch(e){showError(e.message);}

function refreshExamples(){
 const examples=createExamplePrompts([...selected],catalog,{startYear:$('#start-year').value,endYear:$('#end-year').value,observationDate:$('#observation-date').value});
 const current=$('#prompt').value;
 $('#suggestions').innerHTML=examples.length?'<span>선택한 카드에 맞춘 예시</span>':'<span>카드를 선택하면 맞춤 예시가 생성됩니다.</span>';
 examples.forEach(example=>{const button=document.createElement('button');button.textContent=example.label;button.disabled=busy;button.onclick=()=>{if(busy)return;$('#prompt').value=example.prompt;lastGeneratedPrompt=example.prompt;$('#char-count').textContent=`${example.prompt.length} / 2,000`;updateButtons();};$('#suggestions').append(button);});
 if(!current.trim()||current===lastGeneratedPrompt){$('#prompt').value=examples[0]?.prompt||'';lastGeneratedPrompt=$('#prompt').value;}
 $('#char-count').textContent=`${$('#prompt').value.length} / 2,000`;updateButtons();
}
['#start-year','#end-year','#observation-date'].forEach(id=>$(id).addEventListener('change',()=>{invalidate();refreshExamples();}));
